-- Tests for the reStructuredText to Markdown conversion behind 'gdev.docs'.
-- Like 'gdev.util' and 'gdev.project' this is an internal module with no
-- `setup()`, so the baseline that applies is the per-function one.
--
-- It is tested here rather than through 'gdev.docs' on purpose: this is the one
-- pure, wholly deterministic part of that pipeline, and every case below would
-- otherwise be buried behind a fetch and a window.
local helpers = dofile('tests/helpers.lua')

local child = helpers.new_child_neovim()
local eq = helpers.expect.equality
local new_set = MiniTest.new_set

local load_rst = function()
  child.lua([[_G.Rst = require('gdev.rst')]])
end

local convert = function(rst)
  return child.lua_get('Rst.to_markdown(...)', { rst })
end
local inline = function(text)
  return child.lua_get('Rst.inline(...)', { text })
end

-- Output test set ============================================================
local T = new_set({
  hooks = {
    pre_case = function()
      child.setup()
      load_rst()
    end,
    post_once = child.stop,
  },
  n_retry = helpers.get_n_retry(1),
})

-- Unit tests =================================================================
T['to_markdown()'] = new_set()

T['to_markdown()']['converts underlined titles to headings'] = function()
  local rst = [[
Node
====

Description
-----------

Signature
~~~~~~~~~

Detail
^^^^^^

Aside
"""""
]]

  eq(convert(rst), '# Node\n\n## Description\n\n### Signature\n\n#### Detail\n\n##### Aside')
end

T['to_markdown()']['ignores an underline shorter than its title'] = function()
  -- Sphinx's own error case. The rule is read as a separator instead, which is
  -- what it looks like to everything downstream.
  eq(convert('Some title\n---\n'), 'Some title\n\n---')
end

T['to_markdown()']['keeps a rule of its own as a separator'] = function()
  eq(convert('Above\n\n----\n\nBelow\n'), 'Above\n\n---\n\nBelow')
end

T['to_markdown()']['drops anchors, comments and substitution definitions'] = function()
  local rst = [[
:github_url: hide

.. DO NOT EDIT THIS FILE!!!
.. Generated automatically from Godot engine sources.

.. |const| replace:: :abbr:`const (This method has no side effects.)`

.. _class_Node:

Node
====
]]

  eq(convert(rst), '# Node')
end

T['to_markdown()']['drops a comment together with what is indented under it'] = function()
  eq(convert('.. A comment\n   continued here\n\nText\n'), 'Text')
end

T['to_markdown()']['keeps a code block exactly as it is'] = function()
  -- Indentation, blank lines and trailing whitespace are all content here,
  -- while everywhere else they are noise to be tidied away
  local rst = table.concat({
    '.. code-block:: gdscript',
    '',
    '    func _ready():',
    '        print("hello")   ',
    '',
    '',
    '        print("world")',
    '',
  }, '\n')

  local code = { 'func _ready():', '    print("hello")   ', '', '', '    print("world")' }
  eq(convert(rst), '```gdscript\n' .. table.concat(code, '\n') .. '\n```')
end

T['to_markdown()']['converts the nested code tabs of the class reference'] = function()
  local rst = [[
.. tabs::

 .. code-tab:: gdscript

    var node = Node.new()

 .. code-tab:: csharp

    var node = new Node();
]]

  eq(
    convert(rst),
    '```gdscript\nvar node = Node.new()\n```\n\n```csharp\nvar node = new Node();\n```'
  )
end

T['to_markdown()']['converts admonitions to alerts'] = new_set({
  parametrize = { { 'note', 'NOTE' }, { 'warning', 'WARNING' }, { 'deprecated', 'DEPRECATED' } },
}, {
  test = function(directive, alert)
    local rst = ('.. %s::\n\n\tFirst paragraph.\n\n\tSecond paragraph.\n'):format(directive)

    eq(convert(rst), ('> [!%s]\n> First paragraph.\n>\n> Second paragraph.'):format(alert))
  end,
})

T['to_markdown()']['keeps an admonition argument as its first line'] = function()
  eq(
    convert('.. deprecated:: 4.2\n\n\tUse something else.\n'),
    '> [!DEPRECATED]\n> 4.2\n>\n> Use something else.'
  )
end

T['to_markdown()']['converts grid tables'] = function()
  local rst = [[
+---------+---------+
| Type    | Name    |
+---------+---------+
| int     | count   |
+---------+---------+
]]

  eq(convert(rst), '| Type | Name |\n| --- | --- |\n| int | count |')
end

T['to_markdown()']['converts the indented table of a `.. table::` directive'] = function()
  local rst = [[
.. table::
   :widths: auto

   +-------------------------+------------------------------------------+
   | :ref:`int<class_int>`   | :ref:`priority<class_Node_property_pri>` |
   +-------------------------+------------------------------------------+
]]

  eq(convert(rst), '| `int` | `priority` |\n| --- | --- |')
end

T['to_markdown()']['keeps a substitution out of the table cell split'] = function()
  -- `|const|` marks half the methods in the class reference and carries the
  -- very character a row is split on
  local rst = [[
+-------+--------------------+
| bool  | is_ready |const|   |
+-------+--------------------+
]]

  eq(convert(rst), '| bool | is_ready const |\n| --- | --- |')
end

T['to_markdown()']['joins a table cell wrapped over several rows'] = function()
  local rst = [[
+-------+-------------------+
| Type  | A description     |
|       | continued below   |
+-------+-------------------+
]]

  eq(convert(rst), '| Type | A description continued below |\n| --- | --- |')
end

T['to_markdown()']['pads a short row to the widest one'] = function()
  eq(
    convert('+---+---+\n| a | b |\n+---+---+\n| c |\n+---+---+\n'),
    '| a | b |\n| --- | --- |\n| c |  |'
  )
end

T['to_markdown()']['reads a lone bar line as text, not as a table'] = function()
  -- Every method signature in the reference starts with a `|void|` or
  -- `|const|` substitution
  eq(convert('|void| **add_child**\\ (\\ )\n'), 'void **add_child**()')
end

T['to_markdown()']['keeps the body of an unknown directive'] = function()
  eq(
    convert('.. container:: contribute\n\n\tThere is no description yet.\n'),
    'There is no description yet.'
  )
end

T['to_markdown()']['drops the body of a navigational directive'] = function()
  eq(convert('.. toctree::\n   :maxdepth: 1\n\n   class_node\n   class_object\n\nText\n'), 'Text')
end

T['to_markdown()']['converts lists'] = function()
  local rst = [[
- First item that wraps
  onto a second line
- Second item

1. Step one
2. Step two
]]

  eq(
    convert(rst),
    '- First item that wraps onto a second line\n- Second item\n\n1. Step one\n2. Step two'
  )
end

T['to_markdown()']['joins the lines of a paragraph'] = function()
  eq(
    convert('One line\nand another\n\nA second paragraph\n'),
    'One line and another\n\nA second paragraph'
  )
end

T['to_markdown()']['collapses runs of blank lines'] = function()
  eq(convert('\n\n\nOne\n\n\n\n\nTwo\n\n\n'), 'One\n\nTwo')
end

T['to_markdown()']['accepts CRLF line endings'] = function()
  eq(convert('Node\r\n====\r\n\r\nText.\r\n'), '# Node\n\nText.')
end

T['to_markdown()']['returns an empty string for anything unusable'] = new_set({
  parametrize = { { '' }, { '\n\n' }, { '.. _class_Node:\n' } },
}, {
  test = function(rst)
    eq(convert(rst), '')
  end,
})

T['to_markdown()']['returns an empty string for a non-string'] = function()
  eq(child.lua_get('Rst.to_markdown(nil)'), '')
  eq(child.lua_get('Rst.to_markdown(42)'), '')
end

T['to_markdown()']['converts a whole class page'] = function()
  local page = child.lua_get(
    [[table.concat(vim.fn.readfile('tests/dir-docs/site/classes/class_node.rst'), '\n')]]
  )
  local markdown = convert(page)

  eq(vim.split(markdown, '\n', { plain = true })[1], '# Node')
  eq(markdown:find('## Method Descriptions', 1, true) ~= nil, true)
  eq(markdown:find('| `int` | `process_priority` | `0` |', 1, true) ~= nil, true)
  eq(markdown:find('    add_child(child)', 1, true) ~= nil, true)
  -- Nothing of the markup survives
  eq(markdown:find(':ref:', 1, true), nil)
  eq(markdown:find('.. rst-class', 1, true), nil)
  eq(markdown:find('\\ ', 1, true), nil)
end

T['inline()'] = new_set()

T['inline()']['converts literals'] = function()
  eq(inline('Adds ``node`` to the tree.'), 'Adds `node` to the tree.')
end

T['inline()']['keeps the label of a cross reference'] = function()
  eq(inline(':ref:`Node<class_Node>`'), '`Node`')
  eq(inline(':ref:`bare reference`'), '`bare reference`')
  eq(inline(':doc:`the manual<tutorials/index>`'), 'the manual')
  eq(inline(':doc:`tutorials/index`'), 'tutorials/index')
end

T['inline()']['expands abbreviations'] = function()
  eq(
    inline(':abbr:`const (This method has no side effects.)`'),
    'const (This method has no side effects.)'
  )
end

T['inline()']['converts code-like roles'] = new_set({
  parametrize = { { 'code' }, { 'kbd' }, { 'math' }, { 'literal' }, { 'file' } },
}, {
  test = function(role)
    eq(inline((':%s:`x`'):format(role)), '`x`')
  end,
})

T['inline()']['expands the substitutions of the class reference'] = function()
  eq(inline('**get_name**\\ (\\ ) |const|'), '**get_name**() const')
  eq(inline('|void| **queue_free**\\ (\\ )'), 'void **queue_free**()')
  eq(inline('|bitfield|\\[`int`\\]'), 'BitField[`int`]')
end

T['inline()']['leaves an unknown substitution alone'] = function()
  eq(inline('|whatever| text'), '|whatever| text')
end

T['inline()']['removes escapes'] = function()
  -- An escaped space joins markup to what follows it and is not a character
  eq(
    inline('**add_child**\\ (\\ node\\: :ref:`Node<class_Node>`\\ )'),
    '**add_child**(node: `Node`)'
  )
end

T['inline()']['drops the self-link of a generated definition'] = function()
  eq(inline('**add_child**\\ (\\ ) :ref:`🔗<class_Node_method_add_child>`'), '**add_child**()')
end

T['inline()']['keeps the target of an external link'] = function()
  eq(
    inline('See `the manual <https://docs.godotengine.org/>`__ for more.'),
    'See [the manual](https://docs.godotengine.org/) for more.'
  )
  eq(inline('See `the manual`__ for more.'), 'See the manual for more.')
end

T['inline()']['trims what it returns'] = function()
  eq(inline('   spaced   '), 'spaced')
end

T['inline()']['returns an empty string for anything unusable'] = function()
  eq(inline(''), '')
  eq(child.lua_get('Rst.inline(nil)'), '')
  eq(child.lua_get('Rst.inline(42)'), '')
end

T['substitute()'] = new_set()

T['substitute()']['replaces only the substitutions of the class reference'] = function()
  eq(
    child.lua_get([[Rst.substitute('|const| |virtual| |static| |vararg| |operator| |unknown|')]]),
    'const virtual static vararg operator |unknown|'
  )
end

return T
